//=============================================================================
// This source code file is a part of Wain.
// It defines message and resource ID's
//=============================================================================
#define APSTUDIO_READONLY_SYMBOLS /* Don't let DevStudio mess up this file */

#define IDR_WAINTYPE                    128
#define IDR_MAINFRAME                   129
#define IDD_ABOUTBOX                    131
#define IDD_NAVIGATOR_DIALOG            132
#define IDD_PROJ_SETUP_DIALOG           133
#define IDD_TAG_SETUP_DIALOG            134
#define IDD_SETUP                       135
#define IDD_TAG_LIST_DIALOG             136
#define IDD_COLOR                       137
#define IDD_TOOL_SETUP                  138
#define IDD_TOOL_ARG_BOX                139
#define IDD_SEARCH_DIALOG               140
#define IDD_KEYWORD_SETUP               141
#define IDD_BOOKMARK_LIST_DIALOG        142
#define IDR_COMP_POPUP_MENU             143
#define IDD_KEY_SETUP                   144
#define IDD_MSG_BOX                     145
#define IDD_REPLACE_DIALOG              146
#define IDD_SIMPLE_DIALOG               147
#define IDD_LANG_OPT_SETUP              148
#define IDD_LANG_SEL_SETUP              149
#define IDD_MACRO_SETUP                 150
#define IDD_TAG_SETUP_PROP              151
#define IDC_PAGE_BAR_TAB                152
#define IDD_PAGE_BAR_DIALOG             153
#define IDW_PAGE_BAR                    154
#define IDR_ASSOC_LIST                  155
#define IDD_TEMPLATE_PROP               156
#define IDD_POPUP_MENU_SETUP            159
#define IDD_POPUP_MENU                  160
#define IDL_POPUP_MENU                  161
#define IDV_TAB_VIEW                    162
#define IDR_VIEW_CURSOR                 163
#define IDD_TOOLBAR_DIALOG              164
#define IDD_FILE_INFO_DIALOG            165
#define IDD_PROJ_MANAGE_DIALOG          166
#define IDD_LANG_SEL_NEW_SETUP          167
#define IDD_NAVIGATOR_LIST_COLOR_DLG    168
#define IDD_FTP_CONNECT_DIALOG          169
#define IDC_NAVIGATOR_BAR_TAB           170
#define IDC_FTP_WAIT_DIALOG             171
#define IDC_PRINT_SETUP                 172
#define IDC_CT_POPUP                    173
#define IDC_PROJECT_EDIT_DIALOG         174
#define IDD_WORD_LIST_DIALOG            175
#define IDD_UNDO_TAG_LIST_DIALOG        176
#define IDC_PT_POPUP                    177
#define IDD_CLASS_LIST_DIALOG           178

#define IDM_FIRST_APP_ID                (WM_USER) // 1024
#define IDM_FIRST_MAINFRM_ID            (IDM_FIRST_APP_ID            +  64)
#define IDM_FIRST_NAVIGATOR_BAR_ID      (IDM_FIRST_MAINFRM_ID        + 256)
#define IDM_FIRST_NAVIGATOR_LIST_ID     (IDM_FIRST_NAVIGATOR_BAR_ID  + 128)
#define IDM_FIRST_GLOB_SETUP_ID         (IDM_FIRST_NAVIGATOR_LIST_ID +  64)
#define IDM_FIRST_KEYSETUP_ID           (IDM_FIRST_GLOB_SETUP_ID     +  64)
#define IDM_FIRST_TAGSETUP_ID           (IDM_FIRST_KEYSETUP_ID       +  32)
#define IDM_FIRST_TAGLIST_ID            (IDM_FIRST_TAGSETUP_ID       +  32)
#define IDM_FIRST_VIEW_ID               (IDM_FIRST_TAGLIST_ID        +  32)
#define IDM_FIRST_PROJSETUP_ID          (IDM_FIRST_VIEW_ID           + 256)
#define IDM_FIRST_COLORSETUP_ID         (IDM_FIRST_PROJSETUP_ID      +  64)
#define IDM_FIRST_TOOLSETUP_ID          (IDM_FIRST_COLORSETUP_ID     +  64)
#define IDM_FIRST_SEARCH_ID             (IDM_FIRST_TOOLSETUP_ID      +  64)
#define IDM_FIRST_COMP_ID               (IDM_FIRST_SEARCH_ID         +  64)
#define IDM_FIRST_KEYBOARDSETUP_ID      (IDM_FIRST_COMP_ID           +  64)
#define IDM_FIRST_STATUS_IND_ID         (IDM_FIRST_KEYBOARDSETUP_ID  +  64)
#define IDM_FIRST_SIMPLE_ID             (IDM_FIRST_STATUS_IND_ID     +  64)
#define IDM_FIRST_BOOKMARK_ID           (IDM_FIRST_SIMPLE_ID         +  64)
#define IDM_FIRST_MACRO_SETUP_ID        (IDM_FIRST_BOOKMARK_ID       +  64)
#define IDM_FIRST_LANG_OPT_ID           (IDM_FIRST_MACRO_SETUP_ID    + 128)
#define IDM_FIRST_LANG_SEL_ID           (IDM_FIRST_LANG_OPT_ID       +  32)
#define IDM_FIRST_PAGE_BAR_ID           (IDM_FIRST_LANG_SEL_ID       +  32)
#define IDM_FIRST_ASSOC_LIST_ID         (IDM_FIRST_PAGE_BAR_ID       +  64)
#define IDM_FIRST_TEMP_ID               (IDM_FIRST_ASSOC_LIST_ID     +  64)
#define IDM_FIRST_PUPUP_MENU_SETUP_ID   (IDM_FIRST_TEMP_ID           +  32)
#define IDM_FIRST_FILE_INFO_ID          (IDM_FIRST_PUPUP_MENU_SETUP_ID + 32)
#define IDM_FIRST_PROJ_MANAGE_ID        (IDM_FIRST_FILE_INFO_ID        + 32)
#define IDM_FIRST_DOCK_BAR_ID           (IDM_FIRST_PROJ_MANAGE_ID      + 32)
#define IDM_FIRST_BLC_ID                (IDM_FIRST_DOCK_BAR_ID         + 32)
#define IDC_FIRST_FTP_ID                (IDM_FIRST_BLC_ID              + 32)
#define IDC_FIRST_FTP_WAIT_DIALOG_ID    (IDC_FIRST_FTP_ID              + 32)
#define IDC_FIRST_PRINT_ID              (IDC_FIRST_FTP_WAIT_DIALOG_ID  + 32)
#define IDC_FIRST_CLASS_TREE_ID         (IDC_FIRST_PRINT_ID            + 32)

#define IDC_MSG_TEXT                    (IDM_FIRST_APP_ID)  // WainMessageBox
#define IDC_MSG_OK                      (IDM_FIRST_APP_ID + 0x01)
#define IDC_MSG_CANCEL                  (IDM_FIRST_APP_ID + 0x02)
#define IDC_MSG_YES                     (IDM_FIRST_APP_ID + 0x04)
#define IDC_MSG_NO                      (IDM_FIRST_APP_ID + 0x08)
#define IDC_MSG_CUST                    (IDM_FIRST_APP_ID + 0x10)
#define IDI_QUESTION_ICO                4128
#define IDI_ERROR_ICO                   4129
#define IDI_WARNING_ICO                 4130
#define IDI_INFORMATION_ICO             4131

#define IDM_SETUP                       (IDM_FIRST_APP_ID + 32)   // App messages
#define IDM_CLOSE_FILE                  (IDM_FIRST_APP_ID + 33)
#define IDC_ABOUT_TIME                  (IDM_FIRST_APP_ID + 34)

#define IDM_SET_FONT                    (IDM_FIRST_MAINFRM_ID + 0)  // MainFrame messages
#define IDM_VIEW_NAVIGATOR_BAR          (IDM_FIRST_MAINFRM_ID + 1)
#define IDM_SEL_NAVIGATOR_BAR           (IDM_FIRST_MAINFRM_ID + 2)
#define IDM_SET_NAVIGATOR_FONT          (IDM_FIRST_MAINFRM_ID + 3)
#define IDM_SEL_NAVIGATOR_LIST          (IDM_FIRST_MAINFRM_ID + 4)
#define IDM_REPLACE                     (IDM_FIRST_MAINFRM_ID + 5)
#define IDM_NEXT_WIN                    (IDM_FIRST_MAINFRM_ID + 6)
#define IDM_PREV_WIN                    (IDM_FIRST_MAINFRM_ID + 7)
#define IDM_NEXT_WIN_HERE               (IDM_FIRST_MAINFRM_ID + 8)
#define IDM_SWAP_WIN                    (IDM_FIRST_MAINFRM_ID + 9)
#define IDM_OTHER_WIN                   (IDM_FIRST_MAINFRM_ID + 10)
#define IDM_VIEW_DIR                    (IDM_FIRST_MAINFRM_ID + 11)
#define IDM_VIEW_FILES                  (IDM_FIRST_MAINFRM_ID + 12)
#define IDM_VIEW_TAGS                   (IDM_FIRST_MAINFRM_ID + 13)
#define IDM_VIEW_PROJ                   (IDM_FIRST_MAINFRM_ID + 14)
#define IDM_VIEW_CURR                   (IDM_FIRST_MAINFRM_ID + 15)
#define IDM_SEARCH                      (IDM_FIRST_MAINFRM_ID + 16)
#define IDM_TOOL_SETUP                  (IDM_FIRST_MAINFRM_ID + 17)
#define IDM_MACRO_SAVE                  (IDM_FIRST_MAINFRM_ID + 18)
#define IDM_MACRO_LOAD                  (IDM_FIRST_MAINFRM_ID + 19)
#define IDM_PROJ_SETUP                  (IDM_FIRST_MAINFRM_ID + 40)
// #define IDM_PROJ_MAKE                   (IDM_FIRST_MAINFRM_ID + 41)
// #define IDM_PROJ_MAKE_ALL               (IDM_FIRST_MAINFRM_ID + 42)
#define IDM_PROJ_ADD_CUR_FILE           (IDM_FIRST_MAINFRM_ID + 44)
#define IDM_PROJ_OPEN                   (IDM_FIRST_MAINFRM_ID + 45)
#define IDM_PROJ_SAVE                   (IDM_FIRST_MAINFRM_ID + 46)
#define IDM_KEY_SETUP                   (IDM_FIRST_MAINFRM_ID + 47)
#define ID_FILE_CHECK_TIMER             (IDM_FIRST_MAINFRM_ID + 48)
#define ID_TOOL_TIMER                   (IDM_FIRST_MAINFRM_ID + 49)
#define IDM_FILE_OPEN                   (IDM_FIRST_MAINFRM_ID + 50)
#define IDM_FILE_NEW                    (IDM_FIRST_MAINFRM_ID + 51)
#define IDM_APP_EXIT                    (IDM_FIRST_MAINFRM_ID + 52)
#define IDM_STATUS_BAR_TIMER            (IDM_FIRST_MAINFRM_ID + 53)
#define IDM_SET_BOOKMARK_0              (IDM_FIRST_MAINFRM_ID + 54)
#define IDM_SET_BOOKMARK_1              (IDM_FIRST_MAINFRM_ID + 55)
#define IDM_SET_BOOKMARK_2              (IDM_FIRST_MAINFRM_ID + 56)
#define IDM_SET_BOOKMARK_3              (IDM_FIRST_MAINFRM_ID + 57)
#define IDM_SET_BOOKMARK_4              (IDM_FIRST_MAINFRM_ID + 58)
#define IDM_SET_BOOKMARK_5              (IDM_FIRST_MAINFRM_ID + 59)
#define IDM_SET_BOOKMARK_6              (IDM_FIRST_MAINFRM_ID + 60)
#define IDM_SET_BOOKMARK_7              (IDM_FIRST_MAINFRM_ID + 61)
#define IDM_SET_BOOKMARK_8              (IDM_FIRST_MAINFRM_ID + 62)
#define IDM_SET_BOOKMARK_9              (IDM_FIRST_MAINFRM_ID + 63)
#define IDM_JUMP_TO_BOOKMARK_0          (IDM_FIRST_MAINFRM_ID + 64)
#define IDM_JUMP_TO_BOOKMARK_1          (IDM_FIRST_MAINFRM_ID + 65)
#define IDM_JUMP_TO_BOOKMARK_2          (IDM_FIRST_MAINFRM_ID + 66)
#define IDM_JUMP_TO_BOOKMARK_3          (IDM_FIRST_MAINFRM_ID + 67)
#define IDM_JUMP_TO_BOOKMARK_4          (IDM_FIRST_MAINFRM_ID + 68)
#define IDM_JUMP_TO_BOOKMARK_5          (IDM_FIRST_MAINFRM_ID + 69)
#define IDM_JUMP_TO_BOOKMARK_6          (IDM_FIRST_MAINFRM_ID + 70)
#define IDM_JUMP_TO_BOOKMARK_7          (IDM_FIRST_MAINFRM_ID + 71)
#define IDM_JUMP_TO_BOOKMARK_8          (IDM_FIRST_MAINFRM_ID + 72)
#define IDM_JUMP_TO_BOOKMARK_9          (IDM_FIRST_MAINFRM_ID + 73)
#define IDM_BOOKMARK_LIST               (IDM_FIRST_MAINFRM_ID + 74)
#define IDM_UNDO_JUMP_TO_TAG            (IDM_FIRST_MAINFRM_ID + 75)
#define IDM_MACRO_SETUP                 (IDM_FIRST_MAINFRM_ID + 90)
#define IDM_DOC_PROP_SETUP              (IDM_FIRST_MAINFRM_ID + 91)
#define IDM_GOTO_OTHER_VIEW             (IDM_FIRST_MAINFRM_ID + 92)
#define IDM_TOOL_OUTPUT_NEXT            (IDM_FIRST_MAINFRM_ID + 93)
#define IDM_TOOL_OUTPUT_PREV            (IDM_FIRST_MAINFRM_ID + 94)
#define IDM_ASSOC_LIST                  (IDM_FIRST_MAINFRM_ID + 95)
#define IDM_VIEW_CALL_TREE              (IDM_FIRST_MAINFRM_ID + 96)
#define IDM_POPUP_MENU_SETUP            (IDM_FIRST_MAINFRM_ID + 97)
#define IDM_SAVE_ALL_DOC                (IDM_FIRST_MAINFRM_ID + 98)
#define IDM_CURR_DOC_PROP_SETUP         (IDM_FIRST_MAINFRM_ID + 99)
#define IDM_VIEW_TOOLBAR                (IDM_FIRST_MAINFRM_ID + 100)
#define IDM_PREV_WIN_HERE               (IDM_FIRST_MAINFRM_ID + 101)
#define IDM_PROJ_MANAGE                 (IDM_FIRST_MAINFRM_ID + 102)
#define IDM_LAST_AUTO_TAG               (IDM_FIRST_MAINFRM_ID + 103)
#define IDM_USER_MENU_SETUP             (IDM_FIRST_MAINFRM_ID + 104)
#define IDM_CLEANUP_TIMER               (IDM_FIRST_MAINFRM_ID + 105)
#define IDM_RECENT_PROJ0                (IDM_FIRST_MAINFRM_ID + 106)
#define IDM_RECENT_PROJ1                (IDM_FIRST_MAINFRM_ID + 107)
#define IDM_RECENT_PROJ2                (IDM_FIRST_MAINFRM_ID + 108)
#define IDM_RECENT_PROJ3                (IDM_FIRST_MAINFRM_ID + 109)
#define IDM_RECENT_PROJ4                (IDM_FIRST_MAINFRM_ID + 110)
#define IDM_RECENT_PROJ5                (IDM_FIRST_MAINFRM_ID + 111)
#define IDM_RECENT_PROJ6                (IDM_FIRST_MAINFRM_ID + 112)
#define IDM_RECENT_PROJ7                (IDM_FIRST_MAINFRM_ID + 113)
#define IDM_RECENT_PROJ8                (IDM_FIRST_MAINFRM_ID + 114)
#define IDM_RECENT_PROJ9                (IDM_FIRST_MAINFRM_ID + 115)
#define IDM_VIEW_CLASS                  (IDM_FIRST_MAINFRM_ID + 116)
#define IDM_TAB_VIEW_COLOR              (IDM_FIRST_MAINFRM_ID + 117)
#define IDM_SEND_TOOL_CMD               (IDM_FIRST_MAINFRM_ID + 118)
#define IDM_PROJECT_REPLACE             (IDM_FIRST_MAINFRM_ID + 119)
#define IDM_GLOBAL_REPLACE              (IDM_FIRST_MAINFRM_ID + 120)
#define IDM_PROJ_MAKE                   (IDM_FIRST_MAINFRM_ID + 121)
#define IDM_PROJ_MAKE_0                 (IDM_FIRST_MAINFRM_ID + 122)
#define IDM_PROJ_MAKE_1                 (IDM_FIRST_MAINFRM_ID + 123)
#define IDM_PROJ_MAKE_2                 (IDM_FIRST_MAINFRM_ID + 124)
#define IDM_PROJ_MAKE_3                 (IDM_FIRST_MAINFRM_ID + 125)
#define IDM_PROJ_MAKE_4                 (IDM_FIRST_MAINFRM_ID + 126)
#define IDM_PROJ_EXE                    (IDM_FIRST_MAINFRM_ID + 127)
#define IDM_PROJ_EXE_1                  (IDM_FIRST_MAINFRM_ID + 128)
#define IDM_PROJ_EXE_2                  (IDM_FIRST_MAINFRM_ID + 129)
#define IDM_PROJ_EXE_3                  (IDM_FIRST_MAINFRM_ID + 130)
#define IDM_PROJ_EXE_4                  (IDM_FIRST_MAINFRM_ID + 131)
#define IDM_RUN_MACRO_0                 (IDM_FIRST_MAINFRM_ID + 132)
#define MAX_NUM_MACRO  32
#define IDM_RUN_MACRO_LAST              (IDM_RUN_MACRO_0 + MAX_NUM_MACRO)
#define IDM_REDO_LAST_TAG               (IDM_RUN_MACRO_LAST + 1)
#define IDM_RUN_TOOL_0                  (IDM_FIRST_MAINFRM_ID + 200)
#define IDM_RUN_TOOL_1                  (IDM_FIRST_MAINFRM_ID + 201)
#define IDM_RUN_TOOL_2                  (IDM_FIRST_MAINFRM_ID + 202)
#define IDM_RUN_TOOL_3                  (IDM_FIRST_MAINFRM_ID + 203)
#define IDM_RUN_TOOL_4                  (IDM_FIRST_MAINFRM_ID + 204)
#define IDM_RUN_TOOL_5                  (IDM_FIRST_MAINFRM_ID + 205)
#define IDM_RUN_TOOL_6                  (IDM_FIRST_MAINFRM_ID + 206)
#define IDM_RUN_TOOL_7                  (IDM_FIRST_MAINFRM_ID + 207)
#define IDM_RUN_TOOL_8                  (IDM_FIRST_MAINFRM_ID + 208)
#define IDM_RUN_TOOL_9                  (IDM_FIRST_MAINFRM_ID + 209)
#define IDM_RUN_TOOL_10                 (IDM_FIRST_MAINFRM_ID + 210)
#define IDM_RUN_TOOL_11                 (IDM_FIRST_MAINFRM_ID + 211)
#define IDM_RUN_TOOL_12                 (IDM_FIRST_MAINFRM_ID + 212)
#define IDM_RUN_TOOL_13                 (IDM_FIRST_MAINFRM_ID + 213)
#define IDM_RUN_TOOL_14                 (IDM_FIRST_MAINFRM_ID + 214)
#define IDM_RUN_TOOL_15                 (IDM_FIRST_MAINFRM_ID + 215)
#define IDM_RUN_TOOL_16                 (IDM_FIRST_MAINFRM_ID + 216)
#define IDM_RUN_TOOL_17                 (IDM_FIRST_MAINFRM_ID + 217)
#define IDM_RUN_TOOL_18                 (IDM_FIRST_MAINFRM_ID + 218)
#define IDM_RUN_TOOL_19                 (IDM_FIRST_MAINFRM_ID + 219)

#define IDB_COMBO                       (IDM_FIRST_NAVIGATOR_BAR_ID + 0) // NavigatorBar
#define IDB_TAG_INDEX_TIMER             (IDM_FIRST_NAVIGATOR_BAR_ID + 2)
#define IDB_REREAD                      (IDM_FIRST_NAVIGATOR_BAR_ID + 6)
#define IDB_TAG_BUILD                   (IDM_FIRST_NAVIGATOR_BAR_ID + 7)
#define IDB_MAKE                        (IDM_FIRST_NAVIGATOR_BAR_ID + 8)
#define IDB_SETUP                       (IDM_FIRST_NAVIGATOR_BAR_ID + 9)
#define IDB_OPEN                        (IDM_FIRST_NAVIGATOR_BAR_ID + 10)
#define IDB_TAG_REBUILD                 (IDM_FIRST_NAVIGATOR_BAR_ID + 12)
#define IDB_TAG_SETUP                   (IDM_FIRST_NAVIGATOR_BAR_ID + 13)
#define IDB_HEADER                      (IDM_FIRST_NAVIGATOR_BAR_ID + 14)
#define IDB_TAG_DONE                    (IDM_FIRST_NAVIGATOR_BAR_ID + 15)
#define IDB_SEARCH                      (IDM_FIRST_NAVIGATOR_BAR_ID + 16)
#define IDB_NEXT                        (IDM_FIRST_NAVIGATOR_BAR_ID + 17)
#define IDB_PREV                        (IDM_FIRST_NAVIGATOR_BAR_ID + 18)
#define IDB_EDIT                        (IDM_FIRST_NAVIGATOR_BAR_ID + 19)
#define IDB_VIEW_DIR                    (IDM_FIRST_NAVIGATOR_BAR_ID + 20)
#define IDB_VIEW_FILES                  (IDM_FIRST_NAVIGATOR_BAR_ID + 21)
#define IDB_VIEW_TAGS                   (IDM_FIRST_NAVIGATOR_BAR_ID + 22)
#define IDB_VIEW_PROJ                   (IDM_FIRST_NAVIGATOR_BAR_ID + 23)
#define IDB_VIEW_CURR                   (IDM_FIRST_NAVIGATOR_BAR_ID + 24)
#define IDB_TAG_REBUILD_TIMER           (IDM_FIRST_NAVIGATOR_BAR_ID + 25)
#define IDB_GLOB_TAG_DONE               (IDM_FIRST_NAVIGATOR_BAR_ID + 26)
#define IDB_AUTO_TAG_DONE               (IDM_FIRST_NAVIGATOR_BAR_ID + 27)
#define IDB_THREAD_MSG                  (IDM_FIRST_NAVIGATOR_BAR_ID + 28)
#define IDB_WORD_THREAD_DONE            (IDM_FIRST_NAVIGATOR_BAR_ID + 29)

#define IDB_AUTO_TAG_FILE_TIMER         (IDM_FIRST_NAVIGATOR_BAR_ID + 29)
#define IDB_MANAGE                      (IDM_FIRST_NAVIGATOR_BAR_ID + 30)
#define IDB_FTP                         (IDM_FIRST_NAVIGATOR_BAR_ID + 31)
#define IDB_VIEW_FTP                    (IDM_FIRST_NAVIGATOR_BAR_ID + 32)
#define IDB_TAG_PEEK                    (IDM_FIRST_NAVIGATOR_BAR_ID + 33)
#define IDB_VIEW_CLASS                  (IDM_FIRST_NAVIGATOR_BAR_ID + 34)

#define IDB_LIST_VIEW                   4096
#define IDB_LIST_TREE                   4097
#define IDB_LIST_TREE_1                 4098
#define IDB_LIST_TREE_2                 4099
#define IDB_LIST_TREE_3                 4100
#define IDB_LIST_TREE_4                 4101
#define IDB_LIST_TREE_5                 4102
#define IDB_LIST_TREE_6                 4103
#define IDB_LIST_TREE_7                 4104
#define IDB_LIST_PROJ_TREE              4105

#define IDL_MOVE_UP                     (IDM_FIRST_NAVIGATOR_LIST_ID +  0) // NavigatorList
#define IDL_MOVE_DOWN                   (IDM_FIRST_NAVIGATOR_LIST_ID +  1)
#define IDL_MOVE_PAGE_UP                (IDM_FIRST_NAVIGATOR_LIST_ID +  2)
#define IDL_MOVE_PAGE_DOWN              (IDM_FIRST_NAVIGATOR_LIST_ID +  3)
#define IDL_MOVE_CTRL_PAGE_UP           (IDM_FIRST_NAVIGATOR_LIST_ID +  4)
#define IDL_DELETE                      (IDM_FIRST_NAVIGATOR_LIST_ID +  5)
#define IDL_INSERT                      (IDM_FIRST_NAVIGATOR_LIST_ID +  6)
#define IDL_SELECT                      (IDM_FIRST_NAVIGATOR_LIST_ID +  7)
#define IDL_COLOR_SETUP                 (IDM_FIRST_NAVIGATOR_LIST_ID +  8)
#define IDL_MOVE_BACK                   (IDM_FIRST_NAVIGATOR_LIST_ID +  9)
#define IDL_VIEW_POPUP                  (IDM_FIRST_NAVIGATOR_LIST_ID + 10)

#define IDC_SETUP_TPATH                 (IDM_FIRST_GLOB_SETUP_ID + 0) // Global Setup
#define IDC_SETUP_IPATH                 (IDM_FIRST_GLOB_SETUP_ID + 1)
#define IDC_CREATE_MAX                  (IDM_FIRST_GLOB_SETUP_ID + 2)
#define IDC_CREATE_DEF                  (IDM_FIRST_GLOB_SETUP_ID + 3)
#define IDC_CREATE_DUAL                 (IDM_FIRST_GLOB_SETUP_ID + 4)
#define IDC_ONE_APP                     (IDM_FIRST_GLOB_SETUP_ID + 5)
#define IDC_LOAD_F                      (IDM_FIRST_GLOB_SETUP_ID + 6)
#define IDC_SETUP_PROJ_EXT              (IDM_FIRST_GLOB_SETUP_ID + 7)
#define ID_SETUP_BROWSE_TPATH           (IDM_FIRST_GLOB_SETUP_ID + 8)
#define ID_SETUP_BROWSE_IPATH           (IDM_FIRST_GLOB_SETUP_ID + 9)
#define IDC_STRIP_WS                    (IDM_FIRST_GLOB_SETUP_ID + 10)
#define IDC_AUTO_REBUILD_CTRL           (IDM_FIRST_GLOB_SETUP_ID + 11)
#define IDC_AUTO_REBUILD_SPIN           (IDM_FIRST_GLOB_SETUP_ID + 12)
#define IDC_MARKING_CUA                 (IDM_FIRST_GLOB_SETUP_ID + 13)
#define IDC_MARKING_COLUMN              (IDM_FIRST_GLOB_SETUP_ID + 14)
#define IDC_TAB_SIZE_EDIT               (IDM_FIRST_GLOB_SETUP_ID + 15)
#define IDC_TAB_SIZE_SPIN               (IDM_FIRST_GLOB_SETUP_ID + 16)
#define IDC_VERT_SCROLLBAR              (IDM_FIRST_GLOB_SETUP_ID + 17)
#define IDC_HORZ_SCROLLBAR              (IDM_FIRST_GLOB_SETUP_ID + 18)
#define IDC_FLUSH_SAVE                  (IDM_FIRST_GLOB_SETUP_ID + 19)
#define IDC_MAX_ENTRIS                  (IDM_FIRST_GLOB_SETUP_ID + 20)
#define IDC_MAX_ENTRIS_EDIT             (IDM_FIRST_GLOB_SETUP_ID + 21)
#define IDC_STICKY_MARK                 (IDM_FIRST_GLOB_SETUP_ID + 22)
#define IDC_VISIBLE_TABS                (IDM_FIRST_GLOB_SETUP_ID + 23)
#define IDC_SHOW_LINE_NO                (IDM_FIRST_GLOB_SETUP_ID + 24)
#define IDC_SHORT_NAMES                 (IDM_FIRST_GLOB_SETUP_ID + 25)
#define IDC_FRAME_LINE                  (IDM_FIRST_GLOB_SETUP_ID + 26)
#define IDC_DEBUG_TOOLS                 (IDM_FIRST_GLOB_SETUP_ID + 27)
#define IDC_USE_USER_MENU               (IDM_FIRST_GLOB_SETUP_ID + 28)
#define IDC_SETUP_TIME_FORMAT           (IDM_FIRST_GLOB_SETUP_ID + 29)
#define IDC_SETUP_DATE_FORMAT           (IDM_FIRST_GLOB_SETUP_ID + 30)
#define IDC_SETUP_TIME_SEP              (IDM_FIRST_GLOB_SETUP_ID + 31)
#define IDC_SETUP_USER_ID               (IDM_FIRST_GLOB_SETUP_ID + 32)
#define IDC_INDENT_EDIT                 (IDM_FIRST_GLOB_SETUP_ID + 33)
#define IDC_INDENT_SPIN                 (IDM_FIRST_GLOB_SETUP_ID + 34)


#define IDC_KEYGROUP_LIST               (IDM_FIRST_KEYSETUP_ID + 0)
#define IDC_KEYWORD_LIST                (IDM_FIRST_KEYSETUP_ID + 1)
#define IDC_KEYWORD_EDIT                (IDM_FIRST_KEYSETUP_ID + 2)
#define IDC_KEYWORD_APPLY               (IDM_FIRST_KEYSETUP_ID + 3)
#define IDC_KEYWORD_DEL                 (IDM_FIRST_KEYSETUP_ID + 4)
#define IDC_KEYWORD_IC                  (IDM_FIRST_KEYSETUP_ID + 5)

#define IDC_TS_PROG                     (IDM_FIRST_TAGSETUP_ID + 0) // TagSetup
#define IDC_TS_OPT                      (IDM_FIRST_TAGSETUP_ID + 1)
#define IDC_TS_FILE                     (IDM_FIRST_TAGSETUP_ID + 2)
#define IDC_TS_TAG_FILE                 (IDM_FIRST_TAGSETUP_ID + 3)
#define IDC_TS_LOOKUP                   (IDM_FIRST_TAGSETUP_ID + 4)
#define IDC_TS_FILES                    (IDM_FIRST_TAGSETUP_ID + 5)
#define IDC_TS_COLOR                    (IDM_FIRST_TAGSETUP_ID + 6)
#define IDC_TS_TRACK                    (IDM_FIRST_TAGSETUP_ID + 7)

#define IDC_TAG_LIST                    (IDM_FIRST_TAGLIST_ID)
#define IDC_TAG_LIST_PEEK               (IDM_FIRST_TAGLIST_ID + 1)
#define IDC_TAG_LIST_TYPE               (IDM_FIRST_TAGLIST_ID + 2)
#define IDC_TAG_LIST_CLASS              (IDM_FIRST_TAGLIST_ID + 3)
#define IDC_TAG_LIST_PEAK_CLASS         (IDM_FIRST_TAGLIST_ID + 4)
#define IDC_WORD_LIST_PEEK              (IDM_FIRST_TAGLIST_ID + 5)
#define IDC_WORD_LIST                   (IDM_FIRST_TAGLIST_ID + 6)

#define FIRST_DISP_VAL                  (IDM_FIRST_VIEW_ID) // View
#define IDV_MOVE_RIGHT                  (IDM_FIRST_VIEW_ID + 0)
#define IDV_MOVE_LEFT                   (IDM_FIRST_VIEW_ID + 1)
#define IDV_MOVE_UP                     (IDM_FIRST_VIEW_ID + 2)
#define IDV_MOVE_DOWN                   (IDM_FIRST_VIEW_ID + 3)
#define IDV_MOVE_PAGE_UP                (IDM_FIRST_VIEW_ID + 4)
#define IDV_MOVE_PAGE_DOWN              (IDM_FIRST_VIEW_ID + 5)
#define IDV_MOVE_HOME                   (IDM_FIRST_VIEW_ID + 6)
#define IDV_MOVE_END                    (IDM_FIRST_VIEW_ID + 7)
#define IDV_SAVE_FILE                   (IDM_FIRST_VIEW_ID + 8)
#define IDV_HANDLE_RETURN               (IDM_FIRST_VIEW_ID + 9)
#define IDV_HANDLE_DELETE               (IDM_FIRST_VIEW_ID + 10)
#define IDV_HANDLE_BACKSPACE            (IDM_FIRST_VIEW_ID + 11)
#define IDV_GOTO_DOC_0                  (IDM_FIRST_VIEW_ID + 12)
#define IDV_GOTO_DOC_1                  (IDM_FIRST_VIEW_ID + 13)
#define IDV_GOTO_DOC_2                  (IDM_FIRST_VIEW_ID + 14)
#define IDV_GOTO_DOC_3                  (IDM_FIRST_VIEW_ID + 15)
#define IDV_GOTO_DOC_4                  (IDM_FIRST_VIEW_ID + 16)
#define IDV_GOTO_DOC_5                  (IDM_FIRST_VIEW_ID + 17)
#define IDV_GOTO_DOC_6                  (IDM_FIRST_VIEW_ID + 18)
#define IDV_GOTO_DOC_7                  (IDM_FIRST_VIEW_ID + 19)
#define IDV_GOTO_DOC_8                  (IDM_FIRST_VIEW_ID + 20)
#define IDV_GOTO_DOC_9                  (IDM_FIRST_VIEW_ID + 21)
#define IDV_COPY_CLIP                   (IDM_FIRST_VIEW_ID + 22)
#define IDV_MARK_UP                     (IDM_FIRST_VIEW_ID + 23)
#define IDV_MARK_DOWN                   (IDM_FIRST_VIEW_ID + 24)
#define IDV_MARK_CUT                    (IDM_FIRST_VIEW_ID + 25)
#define IDV_PASTE_CLIP                  (IDM_FIRST_VIEW_ID + 26)
#define IDV_MDI_MAX                     (IDM_FIRST_VIEW_ID + 27)
#define IDV_MDI_CAS                     (IDM_FIRST_VIEW_ID + 28)
#define IDV_MARK_RIGHT                  (IDM_FIRST_VIEW_ID + 29)
#define IDV_MARK_LEFT                   (IDM_FIRST_VIEW_ID + 30)
#define IDV_FILE_OPEN_IN_LINE           (IDM_FIRST_VIEW_ID + 31)
#define IDV_EDIT_UNDO                   (IDM_FIRST_VIEW_ID + 32)
#define IDV_INSERT_TOGGLE               (IDM_FIRST_VIEW_ID + 33)
#define IDV_MOVE_WORD_RIGHT             (IDM_FIRST_VIEW_ID + 34)
#define IDV_MOVE_WORD_LEFT              (IDM_FIRST_VIEW_ID + 35)
#define IDV_MARK_WORD_RIGHT             (IDM_FIRST_VIEW_ID + 36)
#define IDV_MARK_WORD_LEFT              (IDM_FIRST_VIEW_ID + 37)
#define IDV_MARK_PAGE_UP                (IDM_FIRST_VIEW_ID + 38)
#define IDV_MARK_PAGE_DOWN              (IDM_FIRST_VIEW_ID + 39)
#define IDV_MARK_HOME                   (IDM_FIRST_VIEW_ID + 40)
#define IDV_MARK_END                    (IDM_FIRST_VIEW_ID + 41)
#define IDV_REMOVE_MARK                 (IDM_FIRST_VIEW_ID + 42)
#define IDV_MARK_WORD                   (IDM_FIRST_VIEW_ID + 43)
#define IDV_INSERT_TAB                  (IDM_FIRST_VIEW_ID + 44)
#define IDV_MDI_DUAL                    (IDM_FIRST_VIEW_ID + 45)
#define IDV_SHIFT_BLOCK_LEFT            (IDM_FIRST_VIEW_ID + 46)
#define IDV_SHIFT_BLOCK_RIGHT           (IDM_FIRST_VIEW_ID + 47)
#define IDV_FIND_MATCH_BRACE            (IDM_FIRST_VIEW_ID + 48)
#define IDV_CUT_SPECIAL                 (IDM_FIRST_VIEW_ID + 49)
#define IDV_COPY_SPECIAL                (IDM_FIRST_VIEW_ID + 50)
#define IDV_PASTE_SPECIAL               (IDM_FIRST_VIEW_ID + 51)
#define IDV_COMP_LIST                   (IDM_FIRST_VIEW_ID + 52)
#define IDV_WORD_COMP                   (IDM_FIRST_VIEW_ID + 53)
#define IDV_COLUMN_MARK                 (IDM_FIRST_VIEW_ID + 54)
#define IDV_MOVE_DOC_START              (IDM_FIRST_VIEW_ID + 55)
#define IDV_MOVE_DOC_END                (IDM_FIRST_VIEW_ID + 56)
#define IDV_GOTO_LINE_NO                (IDM_FIRST_VIEW_ID + 57)
#define IDV_INC_SEARCH                  (IDM_FIRST_VIEW_ID + 58)
#define IDV_SEARCH_NEXT                 (IDM_FIRST_VIEW_ID + 59)
#define IDV_SEARCH_PREV                 (IDM_FIRST_VIEW_ID + 60)
#define IDV_HANDLE_ESC                  (IDM_FIRST_VIEW_ID + 61)
#define IDV_RELOAD_FILE                 (IDM_FIRST_VIEW_ID + 62)
#define IDV_SCROLL_LINE_UP              (IDM_FIRST_VIEW_ID + 63)
#define IDV_SCROLL_LINE_DOWN            (IDM_FIRST_VIEW_ID + 64)
#define IDV_DELETE_WORD                 (IDM_FIRST_VIEW_ID + 65)
#define IDV_INCREASE_MARK_TOP           (IDM_FIRST_VIEW_ID + 66)
#define IDV_INCREASE_MARK_BOT           (IDM_FIRST_VIEW_ID + 67)
#define IDV_DECREASE_MARK_TOP           (IDM_FIRST_VIEW_ID + 68)
#define IDV_DECREASE_MARK_BOT           (IDM_FIRST_VIEW_ID + 69)
#define IDV_EXPAND_TEMPLATE             (IDM_FIRST_VIEW_ID + 70)
#define IDV_MARK_DELETE                 (IDM_FIRST_VIEW_ID + 71)
#define IDV_INDENT_LINE                 (IDM_FIRST_VIEW_ID + 72)
#define IDV_MARK_TOUPPER                (IDM_FIRST_VIEW_ID + 74)
#define IDV_MARK_TOLOWER                (IDM_FIRST_VIEW_ID + 75)
#define IDV_MOVE_NEXT_TAB               (IDM_FIRST_VIEW_ID + 76)
#define IDV_MOVE_PREV_TAB               (IDM_FIRST_VIEW_ID + 77)
#define IDV_INDENT_NEXT_TAB             (IDM_FIRST_VIEW_ID + 78)
#define IDV_INDENT_PREV_TAB             (IDM_FIRST_VIEW_ID + 79)
#define IDV_FILE_INFO                   (IDM_FIRST_VIEW_ID + 80)
#define IDV_SAVE_FILE_AS                (IDM_FIRST_VIEW_ID + 81)
#define IDV_OPEN_AS_DOC                 (IDM_FIRST_VIEW_ID + 82)
#define IDV_TAG_PEEK                    (IDM_FIRST_VIEW_ID + 83)
#define IDV_SCROLL_LOCK                 (IDM_FIRST_VIEW_ID + 84)
#define IDV_MARK_DOC_END                (IDM_FIRST_VIEW_ID + 85)
#define IDV_MARK_DOC_START              (IDM_FIRST_VIEW_ID + 86)
#define IDV_PRINT                       (IDM_FIRST_VIEW_ID + 87)
#define IDV_MOVE_MARK_START             (IDM_FIRST_VIEW_ID + 88)
#define IDV_MOVE_MARK_END               (IDM_FIRST_VIEW_ID + 89)
#define IDV_HANDLE_DELETE_EX            (IDM_FIRST_VIEW_ID + 90)
#define IDV_MACRO_REPEAT                (IDM_FIRST_VIEW_ID + 91)
#define IDV_MOVE_LEFT_EX                (IDM_FIRST_VIEW_ID + 92)
#define IDV_MOVE_RIGHT_EX               (IDM_FIRST_VIEW_ID + 93)
#define IDV_INSERT_DATE                 (IDM_FIRST_VIEW_ID + 94)
#define IDV_INSERT_TIME                 (IDM_FIRST_VIEW_ID + 95)
#define IDV_INSERT_DATE_TIME            (IDM_FIRST_VIEW_ID + 96)
#define IDV_INSERT_TIME_DATE            (IDM_FIRST_VIEW_ID + 97)
#define IDV_INSERT_USER_ID              (IDM_FIRST_VIEW_ID + 98)
#define IDV_REMOVE_TABS                 (IDM_FIRST_VIEW_ID + 99)
#define IDV_HANDLE_RETURN_EX            (IDM_FIRST_VIEW_ID + 100)
#define IDV_GOTO_BLOCK_START            (IDM_FIRST_VIEW_ID + 101)
#define IDV_GOTO_BLOCK_END              (IDM_FIRST_VIEW_ID + 102)
#define IDV_HANDLE_BACKSPACE_EX         (IDM_FIRST_VIEW_ID + 103)
#define IDV_MOVE_HOME_EX                (IDM_FIRST_VIEW_ID + 104)
#define IDV_SHELL_CONTEXT_MENU          (IDM_FIRST_VIEW_ID + 105)

#define IDV_MOVE_WORD_LEFT_EX           (IDM_FIRST_VIEW_ID + 107)
#define IDV_MOVE_WORD_RIGHT_EX          (IDM_FIRST_VIEW_ID + 108)
#define IDV_SCROLL_LINE_CENTER          (IDM_FIRST_VIEW_ID + 109)
#define IDV_SCROLL_LINE_TOP             (IDM_FIRST_VIEW_ID + 110)
#define IDV_SCROLL_LINE_BOTTOM          (IDM_FIRST_VIEW_ID + 111)
#define IDV_NEXT_MATCH_WORD             (IDM_FIRST_VIEW_ID + 112)
#define IDV_PREV_MATCH_WORD             (IDM_FIRST_VIEW_ID + 113)
#define IDV_INSERT_COMMENT              (IDM_FIRST_VIEW_ID + 114)
#define IDV_INSERT_COMMENT_DOWN         (IDM_FIRST_VIEW_ID + 115)
#define IDV_MARK_ALL                    (IDM_FIRST_VIEW_ID + 116)
#define IDV_FIND_MATCH_BLOCK            (IDM_FIRST_VIEW_ID + 117)
#define IDV_COPY_FILE_NAME              (IDM_FIRST_VIEW_ID + 118)
#define IDV_OPEN_DIR_FOR_FILE           (IDM_FIRST_VIEW_ID + 119)
#define IDV_MARK_ALL_WORDS              (IDM_FIRST_VIEW_ID + 120)
#define IDV_MARK_ALL_WORDS_TOGGLE       (IDM_FIRST_VIEW_ID + 121)
#define IDV_MARK_ALL_WORDS_OFF          (IDM_FIRST_VIEW_ID + 122)
#define IDV_OPEN_PROJECT_FOR_FILE       (IDM_FIRST_VIEW_ID + 123)
#define IDV_SWITCH_CPP_H                (IDM_FIRST_VIEW_ID + 124)
#define LAST_DISP_VAL                   (IDM_FIRST_VIEW_ID + 125)

#define ID_PUT_CHAR                     (IDM_FIRST_VIEW_ID + 128)
#define ID_TAG_LIST                     (IDM_FIRST_VIEW_ID + 129)
#define IDM_MACRO_RECORD                (IDM_FIRST_VIEW_ID + 130)
#define IDM_MACRO_PLAYBACK              (IDM_FIRST_VIEW_ID + 131)
#define IDM_MOUSE_MARK_TIMER            (IDM_FIRST_VIEW_ID + 132)
#define ID_TAG_LIST_CLASS               (IDM_FIRST_VIEW_ID + 133)
#define ID_TAG_LIST_DEFINE              (IDM_FIRST_VIEW_ID + 134)
#define ID_TAG_LIST_TYPE                (IDM_FIRST_VIEW_ID + 135)
#define ID_TAG_LIST_STRUCT              (IDM_FIRST_VIEW_ID + 136)
#define ID_TAG_LIST_FUNCTION            (IDM_FIRST_VIEW_ID + 137)
#define ID_TAG_LIST_PROTOTYPE           (IDM_FIRST_VIEW_ID + 138)
#define ID_TAG_LIST_ENUM_NAME           (IDM_FIRST_VIEW_ID + 139)
#define ID_TAG_LIST_ENUM                (IDM_FIRST_VIEW_ID + 140)
#define ID_TAG_LIST_VAR                 (IDM_FIRST_VIEW_ID + 141)
#define ID_TAG_LIST_EXTERN              (IDM_FIRST_VIEW_ID + 142)
#define ID_TAG_LIST_MEMBER              (IDM_FIRST_VIEW_ID + 143)
#define IDM_VIEW_POPUP_MENU             (IDM_FIRST_VIEW_ID + 144)
#define ID_WORD_LIST                    (IDM_FIRST_VIEW_ID + 145)
#define ID_WORD_LIST_REDO               (IDM_FIRST_VIEW_ID + 146)

#define IDM_TOOL_MSG_ID                 (WM_APP + 100)

#define IDM_GET_TAG_LIST                (WM_APP + 202)

#define IDM_PROJ_MAKE_ID                (WM_APP + 205)
#define IDM_PROJ_EXE_ID                 (WM_APP + 206)
#define IDC_PS_FILE                     (IDM_FIRST_PROJSETUP_ID + 3)
#define IDC_PS_BROWSE                   (IDM_FIRST_PROJSETUP_ID + 4)
#define IDC_PS_MAKE_MD                  (IDM_FIRST_PROJSETUP_ID + 5)
#define IDC_PS_MAKE_MW                  (IDM_FIRST_PROJSETUP_ID + 6)
#define IDC_PS_MAKE_SD                  (IDM_FIRST_PROJSETUP_ID + 7)
#define IDC_PS_MAKE_AA                  (IDM_FIRST_PROJSETUP_ID + 8)
#define IDC_PS_MAKE_CSO                 (IDM_FIRST_PROJSETUP_ID + 9)
#define IDC_PS_MAKE_CSE                 (IDM_FIRST_PROJSETUP_ID + 10)
#define IDC_PS_EXE_CSO                  (IDM_FIRST_PROJSETUP_ID + 11)
#define IDC_PS_EXE_CSE                  (IDM_FIRST_PROJSETUP_ID + 12)
#define IDC_PS_EXE_MD                   (IDM_FIRST_PROJSETUP_ID + 13)
#define IDC_PS_EXE_MW                   (IDM_FIRST_PROJSETUP_ID + 14)
#define IDC_PS_EXE_AA                   (IDM_FIRST_PROJSETUP_ID + 15)
#define IDC_PS_MAKE_RUN_NORM            (IDM_FIRST_PROJSETUP_ID + 16)
#define IDC_PS_MAKE_RUN_HIDDEN          (IDM_FIRST_PROJSETUP_ID + 17)
#define IDC_PS_INC_PATH                 (IDM_FIRST_PROJSETUP_ID + 19)
#define IDC_PS_INC_BROWSE               (IDM_FIRST_PROJSETUP_ID + 20)
#define IDC_PROJ_TAGS                   (IDM_FIRST_PROJSETUP_ID + 24)
#define IDC_PS_MAKE_LOW                 (IDM_FIRST_PROJSETUP_ID + 29)
#define IDC_PS_EXE_LOW                  (IDM_FIRST_PROJSETUP_ID + 30)
#define IDC_PS_EXE_SAVE                 (IDM_FIRST_PROJSETUP_ID + 31)
#define IDC_PS_EXE_RUN_HIDDEN           (IDM_FIRST_PROJSETUP_ID + 32)
#define IDC_PS_EXE_RUN_NORM             (IDM_FIRST_PROJSETUP_ID + 33)
#define IDC_PS_LINE_REGEXP              (IDM_FIRST_PROJSETUP_ID + 42)
#define IDC_PS_MAKE_ADD                 (IDM_FIRST_PROJSETUP_ID + 43)
#define IDC_PS_MAKE_DELETE              (IDM_FIRST_PROJSETUP_ID + 44)
#define IDC_PS_MAKE_CLONE               (IDM_FIRST_PROJSETUP_ID + 45)
#define IDC_PS_EXE_ADD                  (IDM_FIRST_PROJSETUP_ID + 46)
#define IDC_PS_EXE_DELETE               (IDM_FIRST_PROJSETUP_ID + 47)
#define IDC_PS_EXE_CLONE                (IDM_FIRST_PROJSETUP_ID + 48)

#define IDC_PS_MAKE_GRID                (IDC_PS_LINE_REGEXP + 1)
#define IDC_PS_EXEC_GRID                (IDC_PS_LINE_REGEXP + 2)

#define IDC_COLOR_LIST                  (IDM_FIRST_COLORSETUP_ID + 0) // Color Setup
#define IDC_APPLY                       (IDM_FIRST_COLORSETUP_ID + 1)
#define IDC_RED_SCROLL                  (IDM_FIRST_COLORSETUP_ID + 2)
#define IDC_GREEN_SCROLL                (IDM_FIRST_COLORSETUP_ID + 3)
#define IDC_BLUE_SCROLL                 (IDM_FIRST_COLORSETUP_ID + 4)
#define IDC_COLOR_SAMPLE                (IDM_FIRST_COLORSETUP_ID + 5)
#define IDC_RED_EC                      (IDM_FIRST_COLORSETUP_ID + 6)
#define IDC_BLUE_EC                     (IDM_FIRST_COLORSETUP_ID + 7)
#define IDC_GREEN_EC                    (IDM_FIRST_COLORSETUP_ID + 8)
#define IDC_RED_BG_SCROLL               (IDM_FIRST_COLORSETUP_ID + 9)
#define IDC_GREEN_BG_SCROLL             (IDM_FIRST_COLORSETUP_ID + 10)
#define IDC_BLUE_BG_SCROLL              (IDM_FIRST_COLORSETUP_ID + 11)
#define IDC_RED_BG_EC                   (IDM_FIRST_COLORSETUP_ID + 12)
#define IDC_GREEN_BG_EC                 (IDM_FIRST_COLORSETUP_ID + 13)
#define IDC_BLUE_BG_EC                  (IDM_FIRST_COLORSETUP_ID + 14)
#define IDC_LOAD_SCHEME                 (IDM_FIRST_COLORSETUP_ID + 15)
#define IDC_SAVE_SCHEME                 (IDM_FIRST_COLORSETUP_ID + 16)
#define IDC_VERIFY_COLOR                (IDM_FIRST_COLORSETUP_ID + 17)
#define IDC_CD_SEL_FORG                 (IDM_FIRST_COLORSETUP_ID + 18)
#define IDC_CD_SEL_BACK                 (IDM_FIRST_COLORSETUP_ID + 19)

#define IDC_TOOLS_APPLY                 (IDM_FIRST_TOOLSETUP_ID + 0)  // Tool Setup
#define IDC_TOOLS_LIST                  (IDM_FIRST_TOOLSETUP_ID + 1)
#define IDC_TOOLS_DOS                   (IDM_FIRST_TOOLSETUP_ID + 2)
#define IDC_TOOLS_WINDOWS               (IDM_FIRST_TOOLSETUP_ID + 3)
#define IDC_TOOLS_STDOUT                (IDM_FIRST_TOOLSETUP_ID + 4)
#define IDC_TOOLS_STDERR                (IDM_FIRST_TOOLSETUP_ID + 5)
#define IDC_TOOLS_RUN_NORM              (IDM_FIRST_TOOLSETUP_ID + 6)
#define IDC_TOOLS_RUN_MAX               (IDM_FIRST_TOOLSETUP_ID + 7)
#define IDC_TOOLS_RUN_HIDDEN            (IDM_FIRST_TOOLSETUP_ID + 8)
#define IDC_TOOLS_PROG                  (IDM_FIRST_TOOLSETUP_ID + 9)
#define IDC_TOOLS_ARGS                  (IDM_FIRST_TOOLSETUP_ID + 10)
#define IDC_TOOLS_PATH                  (IDM_FIRST_TOOLSETUP_ID + 11)
#define IDC_TOOLS_MENU_TEXT             (IDM_FIRST_TOOLSETUP_ID + 12)
#define IDC_TOOLS_SAVE                  (IDM_FIRST_TOOLSETUP_ID + 13)
#define IDC_TOOLS_ASK_ARG               (IDM_FIRST_TOOLSETUP_ID + 14)
#define IDC_TOOLS_FIND                  (IDM_FIRST_TOOLSETUP_ID + 15)
#define IDC_TOOLS_NEW                   (IDM_FIRST_TOOLSETUP_ID + 16)
#define IDC_TOOLS_DELETE                (IDM_FIRST_TOOLSETUP_ID + 17)
#define IDC_TOOL_ARG_PROG               (IDM_FIRST_TOOLSETUP_ID + 18)
#define IDC_TOOL_ARG_PATH               (IDM_FIRST_TOOLSETUP_ID + 19)
#define IDC_TOOL_ARG_ARG                (IDM_FIRST_TOOLSETUP_ID + 20)
#define IDC_TOOL_ARG_APPEND             (IDM_FIRST_TOOLSETUP_ID + 21)
#define IDC_TOOLS_APPEND                (IDM_FIRST_TOOLSETUP_ID + 22)
#define IDC_TOOLS_REGEX                 (IDM_FIRST_TOOLSETUP_ID + 23)

#define IDC_SEARCH_COMBO                (IDM_FIRST_SEARCH_ID + 0)
#define IDC_SEARCH_FORWARD              (IDM_FIRST_SEARCH_ID + 1)
#define IDC_SEARCH_BACKWARD             (IDM_FIRST_SEARCH_ID + 2)
#define IDC_SEARCH_START                (IDM_FIRST_SEARCH_ID + 3)
#define IDC_SEARCH_NEXT                 (IDM_FIRST_SEARCH_ID + 4)
#define IDC_SEARCH_CASE                 (IDM_FIRST_SEARCH_ID + 5)
#define IDC_REPLACE_SEARCH_COMBO        (IDM_FIRST_SEARCH_ID + 6)
#define IDC_REPLACE_COMBO               (IDM_FIRST_SEARCH_ID + 7)
#define IDC_REPLACE_FORWARD             (IDM_FIRST_SEARCH_ID + 8)
#define IDC_REPLACE_BACKWARD            (IDM_FIRST_SEARCH_ID + 9)
#define IDC_REPLACE_START               (IDM_FIRST_SEARCH_ID + 10)
#define IDC_REPLACE_CASE                (IDM_FIRST_SEARCH_ID + 11)
#define IDC_REPLACE_SKIP                (IDM_FIRST_SEARCH_ID + 12)
#define IDC_REPLACE_NEXT                (IDM_FIRST_SEARCH_ID + 13)
#define IDC_REPLACE_ALL                 (IDM_FIRST_SEARCH_ID + 14)
#define IDC_SEARCH_REGEX                (IDM_FIRST_SEARCH_ID + 15)
#define IDC_GLOBAL_REPLACE              (IDM_FIRST_SEARCH_ID + 16)

#define IDM_COMP_ITEM0                  (IDM_FIRST_COMP_ID + 0) // Used by completion list popup
#define IDM_COMP_ITEM1                  (IDM_FIRST_COMP_ID + 1)
#define IDM_COMP_ITEM2                  (IDM_FIRST_COMP_ID + 2)
#define IDM_COMP_ITEM3                  (IDM_FIRST_COMP_ID + 3)
#define IDM_COMP_ITEM4                  (IDM_FIRST_COMP_ID + 4)
#define IDM_COMP_ITEM5                  (IDM_FIRST_COMP_ID + 5)
#define IDM_COMP_ITEM6                  (IDM_FIRST_COMP_ID + 6)
#define IDM_COMP_ITEM7                  (IDM_FIRST_COMP_ID + 7)
#define IDM_COMP_ITEM8                  (IDM_FIRST_COMP_ID + 8)
#define IDM_COMP_ITEM9                  (IDM_FIRST_COMP_ID + 9)
#define IDM_COMP_ITEM10                 (IDM_FIRST_COMP_ID + 10)
#define IDM_COMP_ITEM11                 (IDM_FIRST_COMP_ID + 11)
#define IDM_COMP_ITEM12                 (IDM_FIRST_COMP_ID + 12)
#define IDM_COMP_ITEM13                 (IDM_FIRST_COMP_ID + 13)
#define IDM_COMP_ITEM14                 (IDM_FIRST_COMP_ID + 14)
#define IDM_COMP_ITEM15                 (IDM_FIRST_COMP_ID + 15)
#define IDM_COMP_ITEM16                 (IDM_FIRST_COMP_ID + 16)
#define IDM_COMP_ITEM17                 (IDM_FIRST_COMP_ID + 17)
#define IDM_COMP_ITEM18                 (IDM_FIRST_COMP_ID + 18)
#define IDM_COMP_ITEM19                 (IDM_FIRST_COMP_ID + 19)

#define IDM_ASSOC_ITEM0                 (IDM_FIRST_ASSOC_LIST_ID + 0)
#define IDM_ASSOC_ITEM1                 (IDM_FIRST_ASSOC_LIST_ID + 1)
#define IDM_ASSOC_ITEM2                 (IDM_FIRST_ASSOC_LIST_ID + 2)
#define IDM_ASSOC_ITEM3                 (IDM_FIRST_ASSOC_LIST_ID + 3)
#define IDM_ASSOC_ITEM4                 (IDM_FIRST_ASSOC_LIST_ID + 4)
#define IDM_ASSOC_ITEM5                 (IDM_FIRST_ASSOC_LIST_ID + 5)
#define IDM_ASSOC_ITEM6                 (IDM_FIRST_ASSOC_LIST_ID + 6)
#define IDM_ASSOC_ITEM7                 (IDM_FIRST_ASSOC_LIST_ID + 7)
#define IDM_ASSOC_ITEM8                 (IDM_FIRST_ASSOC_LIST_ID + 8)
#define IDM_ASSOC_ITEM9                 (IDM_FIRST_ASSOC_LIST_ID + 9)

#define IDC_KEY_FUNC                    (IDM_FIRST_KEYBOARDSETUP_ID + 0) // Keyboard Setup
#define IDC_KEY_KEY                     (IDM_FIRST_KEYBOARDSETUP_ID + 1)
#define IDC_KEY_ALT                     (IDM_FIRST_KEYBOARDSETUP_ID + 2)
#define IDC_KEY_CTRL                    (IDM_FIRST_KEYBOARDSETUP_ID + 3)
#define IDC_KEY_SHIFT                   (IDM_FIRST_KEYBOARDSETUP_ID + 4)
#define IDC_KEY_APPLY                   (IDM_FIRST_KEYBOARDSETUP_ID + 5)
#define IDC_KEY_REMOVE                  (IDM_FIRST_KEYBOARDSETUP_ID + 6)
#define IDC_KEY_CURR                    (IDM_FIRST_KEYBOARDSETUP_ID + 7)
#define IDC_KEY_BROWSE                  (IDM_FIRST_KEYBOARDSETUP_ID + 8)
#define IDC_KEY_FILE                    (IDM_FIRST_KEYBOARDSETUP_ID + 9)

#define ID_SB_LINE_STATUS               (IDM_FIRST_STATUS_IND_ID + 0) // Status Bar Indicators
#define ID_SB_MARK_STATUS               (IDM_FIRST_STATUS_IND_ID + 1)
#define ID_SB_INS_STATUS                (IDM_FIRST_STATUS_IND_ID + 2)
#define ID_SB_MACRO_REC                 (IDM_FIRST_STATUS_IND_ID + 3)
#define ID_SB_MOD_STATUS                (IDM_FIRST_STATUS_IND_ID + 4)
#define ID_SB_STATUS_TEXT               (IDM_FIRST_STATUS_IND_ID + 5)
#define ID_SB_SPECIAL_MODE              (IDM_FIRST_STATUS_IND_ID + 6)
#define ID_SB_CRLF_STATUS               (IDM_FIRST_STATUS_IND_ID + 7)
#define ID_SB_SCROLL_LOCK               (IDM_FIRST_STATUS_IND_ID + 8)
#define ID_SB_READ_ONLY                 (IDM_FIRST_STATUS_IND_ID + 9)

#define IDC_MACRO_MENUTEXT              (IDM_FIRST_MACRO_SETUP_ID + 0)
#define IDC_MACRO_REMOVE                (IDM_FIRST_MACRO_SETUP_ID + 1)
#define IDC_MACRO_FIND                  (IDM_FIRST_MACRO_SETUP_ID + 2)
#define IDC_MACRO_FILENAME_EDIT         (IDM_FIRST_MACRO_SETUP_ID + 3)
#define IDC_MACRO_MENUTEXT_EDIT         (IDM_FIRST_MACRO_SETUP_ID + 4)
#define IDC_MACRO_APPLY                 (IDM_FIRST_MACRO_SETUP_ID + 5)
#define IDC_MACRO_NEW                   (IDM_FIRST_MACRO_SETUP_ID + 6)

#define IDC_SIMPLE_EDIT                 IDM_FIRST_SIMPLE_ID
#define IDC_BOOKMARK_LIST               IDM_FIRST_BOOKMARK_ID
#define IDC_TAG_JUMP_LIST               (IDM_FIRST_BOOKMARK_ID + 1)

#define IDC_LO_SEPS                     (IDM_FIRST_LANG_OPT_ID +  0)
#define IDC_LO_BBEGIN                   (IDM_FIRST_LANG_OPT_ID +  1)
#define IDC_LO_BEND                     (IDM_FIRST_LANG_OPT_ID +  2)
#define IDC_LO_BRACES                   (IDM_FIRST_LANG_OPT_ID +  4)
#define IDC_LO_STRING                   (IDM_FIRST_LANG_OPT_ID +  5)
#define IDC_LO_CHAR                     (IDM_FIRST_LANG_OPT_ID +  6)
#define IDC_LO_LINE_COMMENT             (IDM_FIRST_LANG_OPT_ID +  7)
#define IDC_LO_COMMENT_BEGIN            (IDM_FIRST_LANG_OPT_ID +  8)
#define IDC_LO_COMMENT_END              (IDM_FIRST_LANG_OPT_ID +  9)
#define IDC_LO_PREPROCESSOR             (IDM_FIRST_LANG_OPT_ID + 10)
#define IDC_LO_COM_WHOLE_WORDS          (IDM_FIRST_LANG_OPT_ID + 11)
#define IDC_LO_LITERAL                  (IDM_FIRST_LANG_OPT_ID + 12)
#define IDC_LO_LINE_CON                 (IDM_FIRST_LANG_OPT_ID + 13)
#define IDC_LO_TAB_POS                  (IDM_FIRST_LANG_OPT_ID + 14)
#define IDC_LO_PREPROC_WORDS            (IDM_FIRST_LANG_OPT_ID + 15)
#define IDC_LO_NUMBER_STR               (IDM_FIRST_LANG_OPT_ID + 16)
#define IDC_LO_COM_FIRST_WORD           (IDM_FIRST_LANG_OPT_ID + 17)
#define IDC_LO_INDENT_AFTER             (IDM_FIRST_LANG_OPT_ID + 18)
#define IDC_LO_INDENT_UNLESS            (IDM_FIRST_LANG_OPT_ID + 19)
#define IDC_LO_UNINDENT                 (IDM_FIRST_LANG_OPT_ID + 20)
#define IDC_LO_BLOCK_START_WORDS        (IDM_FIRST_LANG_OPT_ID + 21)
#define IDC_LO_BLOCK_END_WORDS          (IDM_FIRST_LANG_OPT_ID + 22)

#define IDC_LS_TYPE_LIST                (IDM_FIRST_LANG_SEL_ID + 0)
#define IDC_LS_EXT_LIST                 (IDM_FIRST_LANG_SEL_ID + 1)
#define IDC_LS_SELECT                   (IDM_FIRST_LANG_SEL_ID + 2)
#define IDC_LS_EXT_EDIT                 (IDM_FIRST_LANG_SEL_ID + 3)
#define IDC_LS_TYPE_EDIT                (IDM_FIRST_LANG_SEL_ID + 4)
#define IDC_LS_CLONE                    (IDM_FIRST_LANG_SEL_ID + 5)
#define IDC_LS_NEW                      (IDM_FIRST_LANG_SEL_ID + 6)
#define IDC_LS_REMOVE                   (IDM_FIRST_LANG_SEL_ID + 7)
#define IDC_LS_N_TYPE_EDIT              (IDM_FIRST_LANG_SEL_ID + 8)
#define IDC_LS_N_EXT_EDIT               (IDM_FIRST_LANG_SEL_ID + 9)
#define IDC_LS_N_FILE_EDIT              (IDM_FIRST_LANG_SEL_ID + 10)


#define IDC_PAGE_BAR_BUTTON             (IDM_FIRST_PAGE_BAR_ID + 0)
#define IDM_PAGE_BAR_TIMER              (IDM_FIRST_PAGE_BAR_ID + 1)

#define IDC_TEMP_LIST                   (IDM_FIRST_TEMP_ID + 0)
#define IDC_TEMP_EDIT                   (IDM_FIRST_TEMP_ID + 1)
#define IDC_TEMP_DELETE                 (IDM_FIRST_TEMP_ID + 2)
#define IDC_TEMP_NEW                    (IDM_FIRST_TEMP_ID + 3)
#define IDC_TEMP_OK                     (IDM_FIRST_TEMP_ID + 4)

#define IDB_SMALLICONS                  4096

#define IDC_PMS_ADD                     (IDM_FIRST_PUPUP_MENU_SETUP_ID + 0)
#define IDC_PMS_REMOVE                  (IDM_FIRST_PUPUP_MENU_SETUP_ID + 1)
#define IDC_PMS_SEPERATOR               (IDM_FIRST_PUPUP_MENU_SETUP_ID + 2)
#define IDC_PMS_UP                      (IDM_FIRST_PUPUP_MENU_SETUP_ID + 3)
#define IDC_PMS_DOWN                    (IDM_FIRST_PUPUP_MENU_SETUP_ID + 4)
#define IDC_PMS_FUNC_LIST               (IDM_FIRST_PUPUP_MENU_SETUP_ID + 5)
#define IDC_PMS_MENU_LIST               (IDM_FIRST_PUPUP_MENU_SETUP_ID + 6)

#define IDC_FILE_INFO_LINES             (IDM_FIRST_FILE_INFO_ID + 0)
#define IDC_FILE_INFO_CHARS             (IDM_FIRST_FILE_INFO_ID + 1)
#define IDC_FILE_INFO_UNIX              (IDM_FIRST_FILE_INFO_ID + 2)
#define IDC_FILE_INFO_READONLY          (IDM_FIRST_FILE_INFO_ID + 3)

#define IDC_PM_CURR_TREE                (IDM_FIRST_PROJ_MANAGE_ID + 0)
#define IDC_PM_CURR_DIR                 (IDM_FIRST_PROJ_MANAGE_ID + 1)
#define IDC_PM_ADD                      (IDM_FIRST_PROJ_MANAGE_ID + 2)
#define IDC_PM_REMOVE                   (IDM_FIRST_PROJ_MANAGE_ID + 3)
#define IDC_PM_DISK_COMBO               (IDM_FIRST_PROJ_MANAGE_ID + 4)
#define IDC_PM_FILTER_COMBO             (IDM_FIRST_PROJ_MANAGE_ID + 5)
#define IDC_PM_CURRENT_PATH             (IDM_FIRST_PROJ_MANAGE_ID + 6)
#define IDC_PM_HOME                     (IDM_FIRST_PROJ_MANAGE_ID + 7)

#define IDM_DOCK_BAR_TIMER              (IDM_FIRST_DOCK_BAR_ID + 0)

#define IDC_BLC_LIST                    (IDM_FIRST_BLC_ID + 0)
#define IDC_BLC_RED_EDIT                (IDM_FIRST_BLC_ID + 1)
#define IDC_BLC_RED_SPIN                (IDM_FIRST_BLC_ID + 2)
#define IDC_BLC_GREEN_EDIT              (IDM_FIRST_BLC_ID + 3)
#define IDC_BLC_GREEN_SPIN              (IDM_FIRST_BLC_ID + 4)
#define IDC_BLC_BLUE_EDIT               (IDM_FIRST_BLC_ID + 5)
#define IDC_BLC_BLUE_SPIN               (IDM_FIRST_BLC_ID + 6)
#define IDC_BLC_COLOR_SAMPLE            (IDM_FIRST_BLC_ID + 7)

#define IDC_FTP_HOSTNAME                (IDC_FIRST_FTP_ID + 0)
#define IDC_FTP_USERNAME                (IDC_FIRST_FTP_ID + 1)
#define IDC_FTP_PASSWORD                (IDC_FIRST_FTP_ID + 2)
#define IDC_FTP_SAVE_PASS               (IDC_FIRST_FTP_ID + 3)
#define IDC_FTP_CONNECT                 (IDC_FIRST_FTP_ID + 4)

#define IDC_FTP_WAIT_STATIC             (IDC_FIRST_FTP_WAIT_DIALOG_ID + 0)
#define IDC_FTP_WAIT_TIMER              (IDC_FIRST_FTP_WAIT_DIALOG_ID + 1)
#define IDC_FTP_WAIT_THREAD_MSG         (IDC_FIRST_FTP_WAIT_DIALOG_ID + 2)

#define IDC_PRINT_COLOR_BW              (IDC_FIRST_PRINT_ID +  0)
#define IDC_PRINT_HEADER                (IDC_FIRST_PRINT_ID +  1)
#define IDC_PRINT_FONT                  (IDC_FIRST_PRINT_ID +  2)
#define IDC_PRINT_LINE_NO               (IDC_FIRST_PRINT_ID +  3)
#define IDC_PRINT_MARGIN                (IDC_FIRST_PRINT_ID +  4)
#define IDC_PRINT_SPIN                  (IDC_FIRST_PRINT_ID +  5)
#define IDC_PRINT_FOOTER                (IDC_FIRST_PRINT_ID +  6)
#define IDC_PRINT_WRAP                  (IDC_FIRST_PRINT_ID +  7)
#define IDC_PRINT_COLOR_DOC             (IDC_FIRST_PRINT_ID +  8)
#define IDC_PRINT_COLOR_SPEC            (IDC_FIRST_PRINT_ID +  9)
#define IDC_PRINT_COLOR                 (IDC_FIRST_PRINT_ID + 10)
#define IDC_PRINT_SCALE                 (IDC_FIRST_PRINT_ID + 11)
#define IDC_PRINT_SCALE_SPIN            (IDC_FIRST_PRINT_ID + 12)

#define IDC_CT_VIEW_POPUP               (IDC_FIRST_CLASS_TREE_ID + 0)
#define IDC_CT_EDIT                     (IDC_FIRST_CLASS_TREE_ID + 1)
#define IDC_CT_TAG_PEEK                 (IDC_FIRST_CLASS_TREE_ID + 2)
#define IDC_CT_TAG_SELECT               (IDC_FIRST_CLASS_TREE_ID + 3)
#define IDC_CT_TAG_EXPAND               (IDC_FIRST_CLASS_TREE_ID + 4)
#define IDC_PT_VIEW_POPUP               (IDC_FIRST_CLASS_TREE_ID + 5)
#define IDC_PT_EDIT                     (IDC_FIRST_CLASS_TREE_ID + 6)

#define IDC_PROJ_EXE_PROG               (IDC_FIRST_CLASS_TREE_ID + 10)
#define IDC_PROJ_EXE_ARG                (IDC_FIRST_CLASS_TREE_ID + 11)
#define IDC_PROJ_EXE_PATH               (IDC_FIRST_CLASS_TREE_ID + 12)
#define IDC_PROJ_EXE_PROG_BROWSE        (IDC_FIRST_CLASS_TREE_ID + 13)
#define IDC_PROJ_EXE_PATH_BROWSE        (IDC_FIRST_CLASS_TREE_ID + 14)
#define IDC_PROJ_EXE_LINE_REGEX         (IDC_FIRST_CLASS_TREE_ID + 15)
#define IDC_PROJ_EXE_PATH_FIND          (IDC_FIRST_CLASS_TREE_ID + 16)
#define IDC_PROJ_EXE_PATH_REPLACE       (IDC_FIRST_CLASS_TREE_ID + 17)
#define IDC_PROJ_EXE_NAME               (IDC_FIRST_CLASS_TREE_ID + 18)
