#ifndef TAG_INDEX_TYPE_H_INC
#define TAG_INDEX_TYPE_H_INC

enum class TagIndexType
{
   CLASS_IDX,
   DEFINE_IDX,
   TYPE_IDX,
   STRUCT_IDX,
   FUNCTION_IDX,
   PROTOTYPE_IDX,
   ENUM_NAME_IDX,
   ENUM_IDX,
   VAR_IDX,
   EXTERN_IDX,
   MEMBER_IDX,
   BLOCK_IDX,
   INTERFACE_IDX,
   TYPE_COMP_IDX,
   LABEL_IDX,
   NAME_SPACE_IDX,
   UNKNOWN_IDX,
   INHERITANCE_IDX,
   NOF_INDEXES
};

#endif